os: osx
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@6.1.0
install:
- travis_wait npm install
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: package.json
  skip_cleanup: true
  on:
    repo: etharner/hello-cordova
    branch: master
    tags: true
#test